apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-guestbook.fullname" . }}
  labels:
    app: {{ include "helm-guestbook.name" . }}
    chart: {{ include "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm-guestbook.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
